/**
 * FreeLang Stage 1 완전 테스트
 * Compiler → VM → 10 + 32 = 42 검증
 */

import { Compiler } from './src/compiler/compiler';
import { ISAGenerator } from './src/compiler/isa-generator';
import { VM, VMDebugger } from './src/vm/vm-executor';

/**
 * Test 1: Compiler 기본 동작
 */
function testCompiler(): number[] {
  console.log('\n📝 Test 1: Compiler (10 + 32 = 42)');
  console.log('─'.repeat(50));

  // 프로그램: a = 10; b = 32; result = a + b;
  const source = `
    a = 10;
    b = 32;
    result = a + b;
  `;

  console.log('Source Code:');
  console.log(source);

  try {
    // 컴파일
    const bytecode = Compiler.compile(source);

    console.log('\n✅ Compilation successful!');
    console.log(`Bytecode length: ${bytecode.length} bytes`);
    console.log(
      `Bytecode (hex): ${bytecode.map((b) => '0x' + b.toString(16).padStart(2, '0')).join(' ')}`
    );

    // Test 1-1: ISA Generator 직접 사용
    console.log('\n📊 Test 1-1: ISA Generator (Low-level)');
    console.log('─'.repeat(50));

    const ast: any = {
      type: 'Program',
      statements: [
        {
          type: 'Assignment',
          target: 'a',
          value: { type: 'NumberLiteral', value: 10 },
        },
        {
          type: 'Assignment',
          target: 'b',
          value: { type: 'NumberLiteral', value: 32 },
        },
        {
          type: 'Assignment',
          target: 'result',
          value: {
            type: 'BinaryOp',
            op: '+',
            left: { type: 'Identifier', name: 'a' },
            right: { type: 'Identifier', name: 'b' },
          },
        },
      ],
    };

    const generator = new ISAGenerator();
    const lowLevelBytecode = generator.generate(ast);

    console.log(`Generated bytecode length: ${lowLevelBytecode.length} bytes`);
    console.log(
      `Bytecode (hex): ${lowLevelBytecode
        .map((b) => '0x' + b.toString(16).padStart(2, '0'))
        .join(' ')}`
    );

    return bytecode;
  } catch (error) {
    console.error('❌ Compilation failed:', error);
    throw error;
  }
}

/**
 * Test 2: VM 실행
 */
function testVM(bytecode: number[]): void {
  console.log('\n⚙️  Test 2: VM Execution');
  console.log('─'.repeat(50));

  try {
    const vm = new VM();

    console.log('Starting VM...');
    const result = vm.run(bytecode);

    console.log('✅ VM execution completed!');
    console.log(`Result (R0): ${result}`);

    if (vm.getException()) {
      console.error(`⚠️  Exception: ${vm.getException()}`);
    }
  } catch (error) {
    console.error('❌ VM execution failed:', error);
    throw error;
  }
}

/**
 * Test 3: 완전 파이프라인 (Compiler → VM)
 */
function testCompletePipeline(): void {
  console.log('\n🔄 Test 3: Complete Pipeline');
  console.log('─'.repeat(50));

  const source = `
    a = 10;
    b = 32;
    result = a + b;
  `;

  console.log('Compiling...');
  const bytecode = Compiler.compile(source);
  console.log(`✅ Bytecode generated (${bytecode.length} bytes)`);

  console.log('\nRunning VM...');
  const vm = new VM();
  const result = vm.run(bytecode);

  console.log(`✅ Execution completed`);
  console.log(`Result: ${result}`);

  // 검증
  if (result === 42) {
    console.log('\n🎉 TEST PASSED: 10 + 32 = 42 ✓');
  } else {
    console.log(`\n❌ TEST FAILED: Expected 42, got ${result}`);
  }
}

/**
 * Test 4: 추가 산술 연산
 */
function testArithmetic(): void {
  console.log('\n🧮 Test 4: Arithmetic Operations');
  console.log('─'.repeat(50));

  const tests = [
    { source: 'a = 5; b = 3; result = a + b;', expected: 8, op: '5 + 3' },
    { source: 'a = 10; b = 3; result = a - b;', expected: 7, op: '10 - 3' },
    { source: 'a = 6; b = 7; result = a * b;', expected: 42, op: '6 * 7' },
    { source: 'a = 84; b = 2; result = a / b;', expected: 42, op: '84 / 2' },
  ];

  for (const test of tests) {
    try {
      console.log(`\nTesting: ${test.op}`);
      const bytecode = Compiler.compile(test.source);
      const vm = new VM();
      const result = vm.run(bytecode);

      if (result === test.expected) {
        console.log(`✅ ${test.op} = ${result} (expected ${test.expected})`);
      } else {
        console.log(
          `⚠️  ${test.op} = ${result} (expected ${test.expected})`
        );
      }
    } catch (error) {
      console.error(`❌ Error in ${test.op}:`, error);
    }
  }
}

/**
 * 메인 테스트 실행
 */
async function main(): Promise<void> {
  console.log('═'.repeat(50));
  console.log('🚀 FreeLang Stage 1: Complete Implementation Test');
  console.log('═'.repeat(50));

  try {
    // Test 1: Compiler
    const bytecode = testCompiler() as number[];

    // Test 2: VM
    testVM(bytecode);

    // Test 3: Complete Pipeline
    testCompletePipeline();

    // Test 4: Arithmetic
    testArithmetic();

    console.log('\n═'.repeat(50));
    console.log('✅ All tests completed!');
    console.log('═'.repeat(50));
  } catch (error) {
    console.error('\n❌ Test suite failed:', error);
    process.exit(1);
  }
}

// 실행
main().catch(console.error);
